name: Update GitHub Stats Gist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm start
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 5b84ef2320331ef6928427877fe2a080
          ALL_COMMITS: true
          K_FORMAT: true
